export const SEED_JOBS = () => {
  const deadline = new Date();
  deadline.setMonth(deadline.getMonth() + 2);

  return [
    {
      title: 'Frontend Developer (React)',
      companyName: 'VNG Corporation',
      location: 'TP. Hồ Chí Minh',
      salary: '20 - 35 trieu',
      salaryMin: 20000000,
      salaryMax: 35000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Middle',
      tags: ['React', 'TypeScript', 'TailwindCSS', 'REST API', 'Git'],
      description:
        'Phat trien va toi uu giao dien cho san pham Zalo Web. Lam viec chat che voi doi ngu Backend va Design.',
      requirements: [
        '2+ nam kinh nghiem React',
        'TypeScript',
        'RESTful API',
        'HTML/CSS',
        'Responsive Design',
        'Git',
      ],
      benefits: ['MacBook Pro', 'Bao hiem suc khoe PVI', 'WFH 2 ngay/tuan'],
      deadline,
      status: 'active',
      featured: true,
      views: 1200,
      applied: 45,
      employerId: '65e123456789012345678901',
    },
    {
      title: 'Senior Backend Engineer (Node.js)',
      companyName: 'MoMo M Service',
      location: 'TP. Hồ Chí Minh',
      salary: '30 - 50 trieu',
      salaryMin: 30000000,
      salaryMax: 50000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Senior',
      tags: [
        'Node.js',
        'TypeScript',
        'MongoDB',
        'Redis',
        'Docker',
        'Microservices',
        'AWS',
      ],
      description:
        'Xay dung he thong xu ly thanh toan hang trieu giao dich moi ngay.',
      requirements: [
        '4+ nam Node.js',
        'Microservices',
        'SQL',
        'Docker',
        'Redis',
        'CI/CD',
      ],
      benefits: ['Thuong KPI', 'Remote flexible', 'Stock options'],
      deadline,
      status: 'active',
      featured: true,
      views: 2100,
      applied: 89,
      employerId: '65e123456789012345678902',
    },
    {
      title: 'UI/UX Designer',
      companyName: 'Grab Vietnam',
      location: 'TP. Hồ Chí Minh',
      salary: '18 - 28 trieu',
      salaryMin: 18000000,
      salaryMax: 28000000,
      category: 'Thiết kế',
      type: 'Toàn thời gian',
      level: 'Middle',
      tags: [
        'Figma',
        'User Research',
        'Prototyping',
        'Design System',
        'Wireframe',
      ],
      description:
        'Thiet ke trai nghiem nguoi dung cho ung dung Grab tai thi truong Viet Nam.',
      requirements: [
        '2+ nam UI/UX',
        'Figma',
        'Portfolio thiet ke',
        'User Research',
        'Prototyping',
      ],
      benefits: ['Grab credits', 'Moi truong quoc te', 'Du lich nuoc ngoai'],
      deadline,
      status: 'active',
      featured: false,
      views: 830,
      applied: 32,
      employerId: '65e123456789012345678903',
    },
    {
      title: 'Data Scientist',
      companyName: 'Tiki Corporation',
      location: 'TP. Hồ Chí Minh',
      salary: '25 - 45 trieu',
      salaryMin: 25000000,
      salaryMax: 45000000,
      category: 'Dữ liệu & AI',
      type: 'Toàn thời gian',
      level: 'Senior',
      tags: [
        'Python',
        'Machine Learning',
        'SQL',
        'Pandas',
        'Spark',
        'TensorFlow',
        'Data Analysis',
      ],
      description:
        'Xay dung mo hinh ML/AI cho he thong goi y san pham va phan tich hanh vi nguoi dung.',
      requirements: [
        '3+ nam Data Science',
        'Python',
        'Machine Learning',
        'SQL',
        'TensorFlow',
        'Statistics',
      ],
      benefits: ['Luong top-market', 'Budget hoc 5tr/nam', 'Flexible hours'],
      deadline,
      status: 'active',
      featured: true,
      views: 1560,
      applied: 67,
      employerId: '65e123456789012345678904',
    },
    {
      title: 'Mobile Developer (React Native)',
      companyName: 'Shopee Vietnam',
      location: 'TP. Hồ Chí Minh',
      salary: '22 - 38 trieu',
      salaryMin: 22000000,
      salaryMax: 38000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Middle',
      tags: [
        'React Native',
        'JavaScript',
        'iOS',
        'Android',
        'Redux',
        'REST API',
        'Git',
      ],
      description: 'Phat trien ung dung di dong Shopee cho ca iOS va Android.',
      requirements: [
        '2+ nam React Native',
        'JavaScript/TypeScript',
        'iOS & Android',
        'Redux',
        'API integration',
      ],
      benefits: ['Com trua mien phi', 'Gym pass', 'Thuong thang 13'],
      deadline,
      status: 'active',
      featured: false,
      views: 945,
      applied: 51,
      employerId: '65e123456789012345678905',
    },
    {
      title: 'DevOps Engineer',
      companyName: 'FPT Software',
      location: 'Hà Nội',
      salary: '25 - 40 trieu',
      salaryMin: 25000000,
      salaryMax: 40000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Senior',
      tags: [
        'Docker',
        'Kubernetes',
        'AWS',
        'CI/CD',
        'Terraform',
        'Linux',
        'Jenkins',
      ],
      description:
        'Quan ly va xay dung ha tang cloud cho cac du an quy mo lon.',
      requirements: [
        '3+ nam DevOps',
        'Docker & Kubernetes',
        'AWS/GCP/Azure',
        'Jenkins',
        'Linux',
        'Terraform',
      ],
      benefits: ['Chung chi AWS tai tro', 'Remote 100%', 'Thiet bi cao cap'],
      deadline,
      status: 'active',
      featured: false,
      views: 720,
      applied: 28,
      employerId: '65e123456789012345678906',
    },
    {
      title: 'Product Manager',
      companyName: 'ZaloPay',
      location: 'TP. Hồ Chí Minh',
      salary: '28 - 50 trieu',
      salaryMin: 28000000,
      salaryMax: 50000000,
      category: 'Quản lý sản phẩm',
      type: 'Toàn thời gian',
      level: 'Senior',
      tags: [
        'Product Management',
        'Agile',
        'Scrum',
        'Analytics',
        'Roadmap',
        'Fintech',
      ],
      description:
        'Dan dat phat trien san pham ZaloPay. Phoi hop voi Engineering va Design.',
      requirements: [
        '3+ nam Product Management',
        'Fintech experience',
        'Agile/Scrum',
        'Data-driven',
        'Communication',
      ],
      benefits: ['Co phan cong ty', 'Xe dua don', 'Mentoring C-level'],
      deadline,
      status: 'active',
      featured: true,
      views: 1890,
      applied: 73,
      employerId: '65e123456789012345678907',
    },
    {
      title: 'Junior Frontend Developer',
      companyName: 'Nexon Games Vietnam',
      location: 'Hà Nội',
      salary: '10 - 18 trieu',
      salaryMin: 10000000,
      salaryMax: 18000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Junior',
      tags: ['HTML', 'CSS', 'JavaScript', 'React', 'Git', 'Responsive Design'],
      description:
        'Vi tri ly tuong cho fresher muon phat trien ky nang React trong moi truong game.',
      requirements: [
        'Tot nghiep nganh CNTT',
        'HTML/CSS/JavaScript',
        'React co ban',
        'Git',
      ],
      benefits: [
        'Mentoring 1 vs 1',
        'Game credits',
        'Lo trinh thang tien ro rang',
      ],
      deadline,
      status: 'active',
      featured: false,
      views: 2300,
      applied: 120,
      employerId: '65e123456789012345678908',
    },
    {
      title: 'Backend Developer (Java Spring Boot)',
      companyName: 'Viettel Digital',
      location: 'Hà Nội',
      salary: '18 - 30 trieu',
      salaryMin: 18000000,
      salaryMax: 30000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Middle',
      tags: [
        'Java',
        'Spring Boot',
        'SQL',
        'MySQL',
        'REST API',
        'Maven',
        'Docker',
      ],
      description:
        'Phat trien he thong backend phuc vu hang trieu khach hang Viettel.',
      requirements: [
        '2+ nam Java Spring Boot',
        'MySQL/PostgreSQL',
        'RESTful API',
        'Maven',
        'Unit Testing',
      ],
      benefits: ['Luong thang 13', 'Bao hiem toan dien', 'Phu cap an trua'],
      deadline,
      status: 'active',
      featured: false,
      views: 1100,
      applied: 55,
      employerId: '65e123456789012345678909',
    },
    {
      title: 'Full Stack Developer (MERN)',
      companyName: 'Sendo',
      location: 'TP. Hồ Chí Minh',
      salary: '20 - 32 trieu',
      salaryMin: 20000000,
      salaryMax: 32000000,
      category: 'Công nghệ thông tin',
      type: 'Toàn thời gian',
      level: 'Middle',
      tags: [
        'MongoDB',
        'Express',
        'React',
        'Node.js',
        'TypeScript',
        'Redux',
        'REST API',
        'Git',
      ],
      description:
        'Xay dung toan bo tinh nang tu frontend den backend cho nen tang thuong mai dien tu Sendo.',
      requirements: [
        '2+ nam Full Stack MERN',
        'React',
        'Node.js',
        'MongoDB',
        'TypeScript',
        'Git',
      ],
      benefits: ['Voucher mua sam', 'WFH thu 6', 'Team building hang quy'],
      deadline,
      status: 'active',
      featured: false,
      views: 850,
      applied: 40,
      employerId: '65e123456789012345678910',
    },
  ];
};
